version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16-browsers
    working_directory: ~/test-lhci
    steps:
      - checkout
      - run: sudo npm install -g @lhci/cli@0.4.x
      - run: lhci collect --url=https://www.ivankristianto.com
      - run: lhci assert
      - run: lhci upload